---
- hosts: wp_prod_terraform
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache
      yum: name=httpd state=present
      
    - name: Install PHP and php-mysql
      command: "amazon-linux-extras install -y php7.2"

    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes

    - name: Extract WordPress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"

    - name: Modify permissions
      file:
        path: /var/www/html/
        recurse: yes
        owner: apache
        group: apache

    - name: Start Apache on boot
      service:
        name: httpd
        state: started
        enabled: yes